export const siteConfig = {
  name: "Ashirwad Agro Exports",
  shortName: "Ashirwad Agro",
  description: "Premium Indian Agricultural Products for Global Markets. B2B bulk supply of ingredients and spices.",
  contact: {
    email: "",
    phone: "", 
    whatsapp: "", 
    whatsappDisplay: "",
    address: "",
  },
  products: [
    {
      id: "onion-powder",
      slug: "onion-powder",
      name: "Onion Powder",
      shortDescription: "Dehydrated onion powder available for commercial requirement discussion.",
      image: "/hero-spices.jpg", 
      imageSpecific: "/onion-powder.jpg",
      applications: ["Spice blends", "Sauces & gravies", "Snack seasonings", "Ready-to-eat meals", "Meat processing"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    },
    {
      id: "garlic-powder",
      slug: "garlic-powder",
      name: "Garlic Powder",
      shortDescription: "Garlic powder available for bulk commercial supply discussion.",
      image: "/hero-spices.jpg",
      imageSpecific: "/garlic-powder.jpg",
      applications: ["Marinades", "Soups & sauces", "Snack flavoring", "Meat packing", "Condiments"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    },
    {
      id: "coriander-powder",
      slug: "coriander-powder",
      name: "Coriander Powder",
      shortDescription: "Ground coriander powder available for bulk commercial supply discussion.",
      image: "/hero-spices.jpg",
      imageSpecific: "/coriander-powder.jpg",
      applications: ["Curry powders", "Bakery products", "Sausage manufacturing", "Pickling", "Marinades"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    },
    {
      id: "moringa-powder",
      slug: "moringa-powder",
      name: "Moringa Powder",
      shortDescription: "Moringa powder available for bulk commercial supply discussion.",
      image: "/hero-spices.jpg",
      imageSpecific: "/moringa-powder.jpg",
      applications: ["Health supplements", "Smoothie blends", "Tea manufacturing", "Nutritional bars", "Fortified foods"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    },
    {
      id: "spice-powders",
      slug: "spice-powders",
      name: "Spice Powders",
      shortDescription: "Various Indian spice powders available for requirement discussion.",
      image: "/hero-spices.jpg",
      imageSpecific: "/other-spices.jpg",
      applications: ["Spice blends", "Food processing", "Catering", "Wholesale distribution", "Restaurant supply"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    },
    {
      id: "masala-spice-blends",
      slug: "masala-spice-blends",
      name: "Masala / Spice Blends",
      shortDescription: "Masala and spice blends available for requirement discussion.",
      image: "/hero-spices.jpg",
      imageSpecific: "/other-spices.jpg",
      applications: ["Commercial kitchens", "Retail repacking", "Ready-to-eat meals", "Marinades", "Snack manufacturing"],
      specifications: "[Specification placeholders to be discussed per buyer requirements]",
      packaging: "[Packaging options arranged per order volume and logistics]",
    }
  ]
};
