export const siteConfig = {
  name: "Ashirwad Agro Exports",
  shortName: "Ashirwad Agro",
  description: "Indian Food Ingredient & Spice Supplier for Kenya. Bulk supply of powders and spices for B2B importers.",
  contact: {
    email: "",
    phone: "", 
    whatsapp: "", 
    whatsappDisplay: "",
    address: "",
  },
  products: [
    {
      id: "onion-powder",
      slug: "onion-powder",
      name: "Onion Powder",
      shortDescription: "Dehydrated onion powder, finely ground for commercial food manufacturing and seasoning blends.",
      image: "/hero-spices.jpg", 
      imageSpecific: "/onion-powder.jpg",
      applications: ["Spice blends", "Sauces & gravies", "Snack seasonings", "Ready-to-eat meals", "Meat processing"],
    },
    {
      id: "garlic-powder",
      slug: "garlic-powder",
      name: "Garlic Powder",
      shortDescription: "Garlic powder for bulk commercial use and distribution.",
      image: "/hero-spices.jpg",
      imageSpecific: "/garlic-powder.jpg",
      applications: ["Marinades", "Soups & sauces", "Snack flavoring", "Meat packing", "Condiments"],
    },
    {
      id: "coriander-powder",
      slug: "coriander-powder",
      name: "Coriander Powder",
      shortDescription: "Ground coriander powder for bulk supply and global spice mixes.",
      image: "/hero-spices.jpg",
      imageSpecific: "/coriander-powder.jpg",
      applications: ["Curry powders", "Bakery products", "Sausage manufacturing", "Pickling", "Marinades"],
    },
    {
      id: "moringa-powder",
      slug: "moringa-powder",
      name: "Moringa Powder",
      shortDescription: "Moringa powder processed for bulk commercial supply.",
      image: "/hero-spices.jpg",
      imageSpecific: "/moringa-powder.jpg",
      applications: ["Health supplements", "Smoothie blends", "Tea manufacturing", "Nutritional bars", "Fortified foods"],
    },
    {
      id: "black-pepper-powder",
      slug: "black-pepper-powder",
      name: "Black Pepper Powder",
      shortDescription: "Black pepper powder ground to meet buyer specifications.",
      image: "/hero-spices.jpg",
      imageSpecific: "/black-pepper-powder.jpg",
      applications: ["Table seasoning", "Meat processing", "Sauces", "Baking", "Preservatives"],
    },
    {
      id: "cinnamon-powder",
      slug: "cinnamon-powder",
      name: "Cinnamon Powder",
      shortDescription: "Cinnamon powder for bakery, confectionery, and spice blending industries.",
      image: "/hero-spices.jpg",
      imageSpecific: "/cinnamon-powder.jpg",
      applications: ["Bakery goods", "Beverages", "Confectionery", "Spice blends", "Desserts"],
    },
    {
      id: "cardamom",
      slug: "cardamom",
      name: "Cardamom",
      shortDescription: "Green cardamom (whole or powdered) for commercial applications.",
      image: "/hero-spices.jpg",
      imageSpecific: "/cardamom.jpg",
      applications: ["Tea blending", "Desserts", "Commercial spice mixes", "Confectionery", "Beverage flavoring"],
    },
    {
      id: "other-spices",
      slug: "other-spices",
      name: "Other Spice Powders",
      shortDescription: "A comprehensive range of Indian spice powders customized to buyer specifications and packaging needs.",
      image: "/hero-spices.jpg",
      imageSpecific: "/other-spices.jpg",
      applications: ["Custom blends", "Food processing", "Catering", "Wholesale distribution", "Restaurant supply"],
    }
  ]
};
